from .eom import load_equations_of_motions, save_equations_of_motions, calculate_equations_of_motions, substitute_params, generate_dynamic_vars, generate_param_vars
from .dynamics.dynamics_with_1_poles import generate_dynamics_with_1_poles
from .dynamics.dynamics_with_2_poles import generate_dynamics_with_2_poles